### ISSUE TITLE
manual install?

### ISSUE THREAD

**Issue by sndcode** [pastasfuture/com.hauntedpsx.render-pipelines.psx#4]
how can i manually install this , when my git installation is not fixable and cannot use the URL method

**Comment by pastasfuture** [comment]
There is no other location to download this package. The only currently supported methods are:
A) Add a git url to your manifest file as outlined in the readme.
B) Use git to clone this repository directly into your [PROJECT_NAME]/Packages/ folder.

Both methods require that you have an up to date version of git and git LFS installed.

I have anecdotally found that cloning via HTTPS rather than SSH seems more reliable with git lfs and unity (switching to HTTPS fixed issues for a few users in the past).
